#!/bin/sh
set -e

. /usr/share/debconf/confmodule

case "$1" in
    configure)
        tmp_file="/tmp/wicard_$$.tmp"
        echo "Downloading @WICARD_URL@"
        curl '@WICARD_URL@' > "$tmp_file"
        install -m 755 "$tmp_file" /usr/bin/wicardd
        rm -f "$tmp_file"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
